import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import Providers from '@/app/providers';
import '@/app/globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html className="dark" lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Providers>
					<div className="flex min-h-screen flex-col">
						<Header />
						<main className="flex flex-1 flex-col">
							<div className="mx-auto w-full max-w-(--breakpoint-xl) flex-1 border-border border-r border-l border-dashed px-8">
								<div className="min-h-[calc(100%-2rem)] w-full pt-10 pb-20">
									{children}
								</div>
							</div>
						</main>
						<Footer />
					</div>
				</Providers>
			</body>
		</html>
	);
}
